-- create Cities table
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS cities(id INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY, state_id INT NOT NULL REFERENCES states (id), name VARCHAR(255) NOT NULL);
INCLUDE FOREIGN KEY (state_id) REFERENCES cities(id);